#Code: Declarando variaveis:
nome_de_cidade = str(input("Nome de uma cidade: "))
numero_de_RG = int(input("Numero de RG: "))
cep = int(input("CEP: "))
telefone = int(input("Numero do telefone: "))
estoque = int(input("Quantidade de produto em estoque: "))
saldo = float(input("Saldo da poupança: "))
faltas = int(input("Faltas em uma disciplina: "))
aprovado = bool(input("Passou ou não passou em uma disciplina: "))
estado_civil = str(input("Estado Civil: "))
chegou_ou_nao = bool(input("Chegou ou não chegou em um lugar: "))